import io.github.zaragozamartin91.staticpropertyanalyser.task.ConfigurableHelloWorldTask
import io.github.zaragozamartin91.staticpropertyanalyser.task.SortPropertiesTask

plugins {
    id 'java'
    id 'io.github.zaragozamartin91.staticpropertyanalyser' version '0.0.1-SNAPSHOT'
}

group = 'io.github.zaragozamartin91'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

tasks.register("configurableHelloWorldTask", ConfigurableHelloWorldTask) {
    group = 'StaticProperties'
    salute = 'hey there'
}

helloWorldExtension {
    salute = 'Salute configured via an extension!'
}

tasks.register("someZip", Zip) {
    from 'src/main/resources'
    from tasks.jar {
        into('lib')
    }

    archiveFileName = 'someZip.zip'
}

/* Testing manual config of SortPropertiesTask */
def sortProperties = tasks.named('sortProperties', SortPropertiesTask)
sortProperties.configure { t ->
    resourceFile = 'application.properties'
}
/* Testing adding dependency of build task with SortPropertiesTask */
tasks.named('build').configure { t ->
    t.dependsOn(sortProperties)
}
