
// Java plugin based on https://github.com/ekim197711/demo-standalone-gradle-plugin/tree/master/src/test/groovy/com/codeinvestigator/plugin

plugins {
	id 'groovy'
	id 'java-gradle-plugin'

	// Publish plugin to local folder
	id 'maven-publish'

	// Gradle publish plugin required to publish to the gradle portal
	// https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#plugin-publishing-plugin
	id 'com.gradle.plugin-publish' version '1.2.1'
}

publishing {
	repositories {
		maven {
			url = layout.buildDirectory.dir('repo')
		}
	}
}

repositories {
	mavenCentral()
}

group = 'io.github.zaragozamartin91'
version = '0.0.1'

/* Setting language level to java 17 */
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

dependencies {
	/* our plugin requires Gradle API interfaces and classes to compile
	* https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html#N17409 */
	implementation gradleApi()

	/* To use the Groovy library that ships with Gradle, declare a localGroovy() dependency
	* https://docs.gradle.org/current/userguide/groovy_plugin.html#sec:groovy_dependency_management */
	implementation localGroovy()

	testImplementation('org.junit.jupiter:junit-jupiter:5.5.2')
	testImplementation('org.spockframework:spock-core:2.2-groovy-3.0') {
		exclude group: 'org.codehaus.groovy'
	}
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
	useJUnitPlatform()
}

gradlePlugin {
	website = 'https://github.com/zaragozamartin91/staticpropertyanalyser'
	vcsUrl = 'https://github.com/zaragozamartin91/staticpropertyanalyser'

	plugins {
		analyserPlugin {
			id = 'io.github.zaragozamartin91.staticpropertyanalyser'
			displayName = 'static-property-analyser'
			description = 'Analyser of static property files'
			tags.set(['property', 'analysis', 'properties', 'yaml', 'spring'])
			implementationClass = 'io.github.zaragozamartin91.staticpropertyanalyser.StaticPropertiesPlugin'
		}
	}
}
